In [4]:
import numpy as np
import pandas as pd
# from sklearn import datasets

# Dense Neural Networks with 2 Hidden Layers

In [5]:
# input data with batch_size=5 & n_features=2
# 5x2 input matrix
inputs = np.array([
          [7, 99],
          [4, 82],
          [8, 51],
          [5, 52],
          [7, 75]
         ])

In [7]:
# feedforward

# first layer with 3 neurons
# n_neurons x n_inputs(=n_feature)
# 3x2 weight matrix
W1 = np.array([
        [0.5, 0.9], 
        [0.5, 0.8],
        [0.6, 0.7]
        ])

# 1x3 bias matrix
# 1xn_neurons
b1 = np.array([2, 3, 1])

# output of the first layer
output1 = np.dot(inputs, W1.T) + b1  #weighted sum 

# second layer with 2 neurons
# 2x3 weight matrix
W2 = np.array([[0.1, 0.14, 0.5], 
               [0.5, 0.12, 0.33]])

# 1x2 bias matrix
b2 = np.array([1, 1])

# output of the second layer
output2 = np.dot(output1, W2.T) + b2

output2

array([[94.6, 85.7, 74.5],
       [77.8, 70.6, 60.8],
       [51.9, 47.8, 41.5],
       [51.3, 47.1, 40.4],
       [73. , 66.5, 57.7]])

In [ ]:
target = np.array([91,65,45,36,66])

In [31]:
# define activation functions
import numpy as np 

def sigmoid(x):
    return 1 / (1+ np.exp(-x))

def relu(x):
    return np.maximum(0, x)

def identity_function(x):
    return x

def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)  #prevent overflow
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

# define loss functions
def cross_entrophy_error(y, t):
    delta = 1e-7  #prevent underflow
    return -np.sum(t * np.log(y+delta))

In [27]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])  #2x3
    network['b1'] = np.array([0.1,0.2,0.3])  
    network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])  #3x2
    network['b2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])  #2x2
    network['b3'] = np.array([0.1,0.2])
    
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    
    a2 = np.dot(z1, W2) + b2
    y = softmax(a2)
    
    # a3 = np.dot(z2, W3) + b3
    # z3 = sigmoid(a3)    
    
    return y

def loss(x, t):
    y = forward(x)
    return cross_entropy_error

In [28]:
network = init_network()
network

{'W1': array([[0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]]),
 'b1': array([0.1, 0.2, 0.3]),
 'W2': array([[0.1, 0.4],
        [0.2, 0.5],
        [0.3, 0.6]]),
 'b2': array([0.1, 0.2]),
 'W3': array([[0.1, 0.3],
        [0.2, 0.4]]),
 'b3': array([0.1, 0.2])}

In [29]:
x = np.array([1.0, 0.5])  #1x2
y = forward(network, x)

[0.3 0.7 1.1] (3,)
(2,)
(2,)


In [26]:
y

array([0.57855079, 0.66736228])

In [ ]:
# backpropagation using the chain rule



# LEARNING PYTORCH WITH EXAMPLES
- https://pytorch.org/tutorials/beginner/pytorch_with_examples.html

In [1]:
import os
import math
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [2]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cuda device


In [3]:
# torch.cuda.device_count()
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4070 Ti'