In [10]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [13]:
data = datasets.load_iris()

In [18]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [17]:
data["data"].shape

(150, 4)

In [19]:
data["target"].shape

(150,)

In [39]:
X = data["data"][:5,:2]
y = data["data"][:5,2]

In [40]:
X

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [29]:
y

array([0, 0, 0, 0, 0])

# Manual Dense Neural Networks with 2 Hidden Layers

In [88]:
# input data with batch size = 5 
# 5x2 matrix
inputs = [[7, 99],
         [4, 82],
         [8, 51],
         [5, 52],
         [7, 75]
    ]
# inputs = [7, 99]
inputs = np.array(inputs)

In [123]:
# first layer with 3 neurons
# 3 x 2 matrix
# n_neurons x n_inputs(=n_feature)
W1 = [[0.5, 0.9], 
      [0.5, 0.8],
      [0.6, 0.7]]
W1 = np.array(W1)

# 1 x 3 matrix
# 1 x n_neurons
b1 = [2, 3, 1]
b1 = np.array(b1)

In [124]:
output1 = np.dot(inputs, W1.T) + b1
output1

array([[94.6, 85.7, 74.5],
       [77.8, 70.6, 60.8],
       [51.9, 47.8, 41.5],
       [51.3, 47.1, 40.4],
       [73. , 66.5, 57.7]])

In [114]:
# second layer with 2 neurons
W2 = [[0.1, 0.14, 0.5], 
     [0.5, 0.12, 0.33]]
W2 = np.array(W2)

b2 = [1, 1]
b2 = np.array(b2)

In [115]:
output1.shape

(5, 3)

In [116]:
W2.shape

(2, 3)

In [119]:
output2 = np.dot(output1, W2.T) + b2
output2
# output2.shape

array([[59.708, 83.169],
       [49.064, 68.436],
       [33.632, 46.381],
       [32.924, 45.634],
       [46.46 , 64.521]])

In [ ]:
target = [91,
         65,
         45,
         36,
         66]
target = np.array(target)

# LEARNING PYTORCH WITH EXAMPLES
- https://pytorch.org/tutorials/beginner/pytorch_with_examples.html

In [1]:
import os
import math
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [2]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cpu device


In [3]:
# torch.cuda.device_count()
torch.cuda.get_device_name(0)

RuntimeError: No CUDA GPUs are available